# Security
security:
  user:
    password: password
    
# External URLs
url:
  base: https://www.racenet.com.au
  form: ${url.base}/form/formguide.aspx?trackcode={0}&shortdate={1}&raceno={2}
  horse: ${url.base}/horse/{0}
  race: ${url.base}/horse-racing-results/{0}/{1}
  jockey: ${url.base}/jockey/{0}